### PR TITLE
A plugin can have jep

### PR DESCRIPTION
**Pull request by martinda**
Explicitly state that a plugin can be the subject of a jep.
@batmat

### CODE REVIEW

**Review by batmat — APPROVED** [review]
I think it makes sense

**Comment by batmat** [comment]
Did you really want to target your own fork @martinda ?

**Comment by martinda** [comment]
@batmat no I did not want to target my own fork, sometimes github baffles me.

**Comment by batmat** [comment]
@martinda let's close this then? :)

**Comment by martinda** [comment]
Sorry for the noise. Yes let's close it.

**Pull request closed without merging**
